name: grunt
on:
  push:
  pull_request:
jobs:
  grunt:
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04, macos-12]
        java: [17]
        node: [16]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - run: npm install
    - run: npm install --force -g grunt-cli
    - run: grunt
